name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: version to tag image
        
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version }}
    steps:
      - name: Setup - checkout
        uses: actions/checkout@v3
        
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: docker
        shell: bash    
        run: docker/docker-build.sh -v ${VERSION}
